nome=input("Whats your name ?")
idade=input("Whats your age ?")
peso=input("Whats your weight")
email=input("Whats your email,please ?")
print("Nice to meet you",nome,"!")
print("Do you fell good about your current weight ?")